### ISSUE TITLE
cannot import name 'main' from 'fvid'

### ISSUE THREAD

**Issue by minhngoc25a** [AlfredoSequeida/fvid#27]
I had ffmpeg in PATH and fvid still doesn't work somehow...

```
PS C:\Users\Tran Bich Dung> py -m fvid -i "[hSa] Daichan, Daisuki. [????, ????.] MOVIE.mp4" -e
Traceback (most recent call last):
  File "C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\lib\site-packages\fvid\__main__.py", line 2, in <module>
    from fvid import main
ImportError: cannot import name 'main' from 'fvid' (C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\lib\site-packages\fvid\__init__.py)
PS C:\Users\Tran Bich Dung> py -m pip install fvid
Requirement already satisfied: fvid in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (0.0.2)
Requirement already satisfied: bitstring in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (3.1.7)
Requirement already satisfied: python-magic in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (0.4.18)
Requirement already satisfied: pillow in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (8.0.1)
Requirement already satisfied: numpy in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (1.19.2)
Requirement already satisfied: tqdm in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (4.51.0)
Requirement already satisfied: ffmpeg-python in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (0.2.0)
Requirement already satisfied: future in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from ffmpeg-python->fvid) (0.18.2)
PS C:\Users\Tran Bich Dung>
```

**Comment by dobrosketchkun** [comment]
I think it's related to https://github.com/AlfredoSequeida/fvid/pull/21#issuecomment-707766115 comment and bellow.
Do you have some kind of Windows, I assume? What version do you have exactly? 

@Theelgirl halp

**Comment by Theelgirl** [comment]
@minhngoc25a @dobrosketchkun It's definitely windows, however I think they need to update fvid. They're using the PyPi version of fvid (0.0.2) where ``from fvid import main`` is on line 2, but on the Github, it's on line 23. @AlfredoSequeida needs to release this to PyPi.

**Comment by Theelgirl** [comment]
@minhngoc25a Try running ``py -m pip install git+https://github.com/AlfredoSequeida/fvid.git#egg=fvid`` and tell us if the error keeps happening.

**Comment by dobrosketchkun** [comment]
I think it'll be better if we first address https://github.com/AlfredoSequeida/fvid/pull/26 and only then update the PyPi version

**Comment by Theelgirl** [comment]
Merged. Is that a feature addition or a patch? 1.0.1 or 1.1.0?

**Comment by dobrosketchkun** [comment]
I think we can classify it as a patch since YouTube is part of the initial idea and functionality. I don't know what to say about the version number; it seems quite arbitrary to me; if there is any convention about it, please use it.

**Comment by Theelgirl** [comment]
The version number is described by [SemVer 2](https://semver.org/).

**Comment by dobrosketchkun** [comment]
Then 1.0.1 it is.

**Comment by minhngoc25a** [comment]
I uninstalled fvid and then used `py -m pip install git+https://github.com/AlfredoSequeida/fvid.git#egg=fvid" as you said. Installation still fails as follow:
```
PS C:\Users\Tran Bich Dung> py -m pip install git+https://github.com/AlfredoSequeida/fvid.git#egg=fvid
Collecting fvid
  Cloning https://github.com/AlfredoSequeida/fvid.git to c:\users\tran bich dung\appdata\local\temp\pip-install-dymix2a1\fvid
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-dymix2a1\\fvid\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-dymix2a1\\fvid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-pip-egg-info-7tthucwj'
         cwd: C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-install-dymix2a1\fvid\
    Complete output (27 lines):
    running egg_info
    creating C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-pip-egg-info-7tthucwj\fvid.egg-info
    writing C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-pip-egg-info-7tthucwj\fvid.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-pip-egg-info-7tthucwj\fvid.egg-info\dependency_links.txt
    writing entry points to C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-pip-egg-info-7tthucwj\fvid.egg-info\entry_points.txt
    writing requirements to C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-pip-egg-info-7tthucwj\fvid.egg-info\requires.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-install-dymix2a1\fvid\setup.py", line 48, in <module>
        setup(
      File "C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\egg_info.py", line 290, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\egg_info.py", line 667, in write_toplevel_names
        [
      File "C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\egg_info.py", line 667, in <listcomp>
        [
      File "C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py", line 985, in iter_distribution_names
        for ext in self.ext_modules or ():
    TypeError: 'Extension' object is not iterable
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Theelgirl** [comment]
@minhngoc25a Can you try now?

**Comment by minhngoc25a** [comment]
Yikes...
https://paste.ubuntu.com/p/mRZvKJxnmV/

**Comment by Theelgirl** [comment]
Yeah try now.

**Comment by minhngoc25a** [comment]
I still use the same command.

```
PS C:\Users\Tran Bich Dung> py -m pip install git+https://github.com/AlfredoSequeida/fvid.git#egg=fvid
Collecting fvid
  Cloning https://github.com/AlfredoSequeida/fvid.git to c:\users\tran bich dung\appdata\local\temp\pip-install-ig31873g\fvid
Requirement already satisfied: bitstring>=3.1.6 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (3.1.7)
Requirement already satisfied: pillow>=7.2.0 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (8.0.1)
Requirement already satisfied: tqdm>=4.49.0 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (4.51.0)
Requirement already satisfied: cryptography>=3.1.1 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (3.2.1)
Requirement already satisfied: pycryptodome>=3.9.8 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (3.9.8)
Requirement already satisfied: six>=1.4.1 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from cryptography>=3.1.1->fvid) (1.15.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from cryptography>=3.1.1->fvid) (1.14.3)
Requirement already satisfied: pycparser in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=3.1.1->fvid) (2.20)
Building wheels for collected packages: fvid
  Building wheel for fvid (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-ig31873g\\fvid\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-ig31873g\\fvid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-wheel-j6_z9ydd'
       cwd: C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-install-ig31873g\fvid\
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\fvid
  copying fvid\cythonizer.py -> build\lib.win-amd64-3.8\fvid
  copying fvid\fvid.py -> build\lib.win-amd64-3.8\fvid
  copying fvid\__init__.py -> build\lib.win-amd64-3.8\fvid
  copying fvid\__main__.py -> build\lib.win-amd64-3.8\fvid
  running egg_info
  creating fvid.egg-info
  writing fvid.egg-info\PKG-INFO
  writing dependency_links to fvid.egg-info\dependency_links.txt
  writing entry points to fvid.egg-info\entry_points.txt
  writing requirements to fvid.egg-info\requires.txt
  writing top-level names to fvid.egg-info\top_level.txt
  writing manifest file 'fvid.egg-info\SOURCES.txt'
  reading manifest file 'fvid.egg-info\SOURCES.txt'
  writing manifest file 'fvid.egg-info\SOURCES.txt'
  copying fvid\fvid_cython.c -> build\lib.win-amd64-3.8\fvid
  running build_ext
  building 'fvid.fvid_cython' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for fvid
  Running setup.py clean for fvid
Failed to build fvid
Installing collected packages: fvid
    Running setup.py install for fvid ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-ig31873g\\fvid\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-ig31873g\\fvid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-record-6vccv61s\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\Include\fvid'
         cwd: C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-install-ig31873g\fvid\
    Complete output (22 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\fvid
    copying fvid\cythonizer.py -> build\lib.win-amd64-3.8\fvid
    copying fvid\fvid.py -> build\lib.win-amd64-3.8\fvid
    copying fvid\__init__.py -> build\lib.win-amd64-3.8\fvid
    copying fvid\__main__.py -> build\lib.win-amd64-3.8\fvid
    running egg_info
    writing fvid.egg-info\PKG-INFO
    writing dependency_links to fvid.egg-info\dependency_links.txt
    writing entry points to fvid.egg-info\entry_points.txt
    writing requirements to fvid.egg-info\requires.txt
    writing top-level names to fvid.egg-info\top_level.txt
    reading manifest file 'fvid.egg-info\SOURCES.txt'
    writing manifest file 'fvid.egg-info\SOURCES.txt'
    copying fvid\fvid_cython.c -> build\lib.win-amd64-3.8\fvid
    running build_ext
    building 'fvid.fvid_cython' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-ig31873g\\fvid\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-ig31873g\\fvid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-record-6vccv61s\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\Include\fvid' Check the logs for full command output.```

**Comment by Theelgirl** [comment]
Ok, can you try once more? I added an except to the part that builds that in order to try and prevent it.

**Comment by minhngoc25a** [comment]
Looks like we're getting somewhere. Less error is shown.
```PS C:\Users\Tran Bich Dung> py -m pip install git+https://github.com/AlfredoSequeida/fvid.git#egg=fvid
Collecting fvid
  Cloning https://github.com/AlfredoSequeida/fvid.git to c:\users\tran bich dung\appdata\local\temp\pip-install-ov408u2i\fvid
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-ov408u2i\\fvid\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-ov408u2i\\fvid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-pip-egg-info-42ki7n0s'
         cwd: C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-install-ov408u2i\fvid\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-install-ov408u2i\fvid\setup.py", line 53
        name="fvid",
            ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by Theelgirl** [comment]
Yeah, I typoed, try it again.

**Comment by minhngoc25a** [comment]
Errors never ends, I guess...
```
PS C:\Users\Tran Bich Dung> py -m pip install git+https://github.com/AlfredoSequeida/fvid.git#egg=fvid
Collecting fvid
  Cloning https://github.com/AlfredoSequeida/fvid.git to c:\users\tran bich dung\appdata\local\temp\pip-install-2cvhkf7f\fvid
Requirement already satisfied: bitstring>=3.1.6 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (3.1.7)
Requirement already satisfied: pillow>=7.2.0 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (8.0.1)
Requirement already satisfied: tqdm>=4.49.0 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (4.51.0)
Requirement already satisfied: cryptography>=3.1.1 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (3.2.1)
Requirement already satisfied: pycryptodome>=3.9.8 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from fvid) (3.9.8)
Requirement already satisfied: six>=1.4.1 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from cryptography>=3.1.1->fvid) (1.15.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from cryptography>=3.1.1->fvid) (1.14.3)
Requirement already satisfied: pycparser in c:\users\tran bich dung\appdata\local\programs\python\python38\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=3.1.1->fvid) (2.20)
Building wheels for collected packages: fvid
  Building wheel for fvid (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-2cvhkf7f\\fvid\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-2cvhkf7f\\fvid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-wheel-36txm_o1'
       cwd: C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-install-2cvhkf7f\fvid\
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\fvid
  copying fvid\cythonizer.py -> build\lib.win-amd64-3.8\fvid
  copying fvid\fvid.py -> build\lib.win-amd64-3.8\fvid
  copying fvid\__init__.py -> build\lib.win-amd64-3.8\fvid
  copying fvid\__main__.py -> build\lib.win-amd64-3.8\fvid
  running egg_info
  creating fvid.egg-info
  writing fvid.egg-info\PKG-INFO
  writing dependency_links to fvid.egg-info\dependency_links.txt
  writing entry points to fvid.egg-info\entry_points.txt
  writing requirements to fvid.egg-info\requires.txt
  writing top-level names to fvid.egg-info\top_level.txt
  writing manifest file 'fvid.egg-info\SOURCES.txt'
  reading manifest file 'fvid.egg-info\SOURCES.txt'
  writing manifest file 'fvid.egg-info\SOURCES.txt'
  copying fvid\fvid_cython.c -> build\lib.win-amd64-3.8\fvid
  running build_ext
  building 'fvid.fvid_cython' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for fvid
  Running setup.py clean for fvid
Failed to build fvid
Installing collected packages: fvid
    Running setup.py install for fvid ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-2cvhkf7f\\fvid\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-2cvhkf7f\\fvid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-record-dt5egsc5\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\Include\fvid'
         cwd: C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-install-2cvhkf7f\fvid\
    Complete output (22 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\fvid
    copying fvid\cythonizer.py -> build\lib.win-amd64-3.8\fvid
    copying fvid\fvid.py -> build\lib.win-amd64-3.8\fvid
    copying fvid\__init__.py -> build\lib.win-amd64-3.8\fvid
    copying fvid\__main__.py -> build\lib.win-amd64-3.8\fvid
    running egg_info
    writing fvid.egg-info\PKG-INFO
    writing dependency_links to fvid.egg-info\dependency_links.txt
    writing entry points to fvid.egg-info\entry_points.txt
    writing requirements to fvid.egg-info\requires.txt
    writing top-level names to fvid.egg-info\top_level.txt
    reading manifest file 'fvid.egg-info\SOURCES.txt'
    writing manifest file 'fvid.egg-info\SOURCES.txt'
    copying fvid\fvid_cython.c -> build\lib.win-amd64-3.8\fvid
    running build_ext
    building 'fvid.fvid_cython' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-2cvhkf7f\\fvid\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tran Bich Dung\\AppData\\Local\\Temp\\pip-install-2cvhkf7f\\fvid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-record-dt5egsc5\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python38\Include\fvid' Check the logs for full command output.
```

**Comment by Theelgirl** [comment]
Ok, I guess you'll need to download it for now, I'll start looking for ways to fix that when I have more time later.

**Comment by minhngoc25a** [comment]
I can't believe that C++ build tools are nearly 5GB...

**Comment by minhngoc25a** [comment]
Maybe I'll switch to WSL

**Comment by Theelgirl** [comment]
Maybe. I just did a last-ditch blanket exception on the setup script, so if this doesn't work, it most likely won't work until we can get someone who's good and experienced with Cython _and_ PyPi.

**Comment by minhngoc25a** [comment]
And right after I install WSL, tried the command in Powershell, it worked. Thanks for your enthusiasm anyway.

**Comment by Theelgirl** [comment]
Ah. Sorry that I couldn't fix it in time :(
