### ISSUE TITLE
No module named 'magic'

### ISSUE THREAD

**Issue by minhngoc25a** [AlfredoSequeida/fvid#41]
I've just started to use fvid again, but:
```
E:\>fvid -i Documents.rar -e -o Documents.mp4
Traceback (most recent call last):
  File "c:\users\tran bich dung\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\tran bich dung\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tran Bich Dung\AppData\Local\Programs\Python\Python39\Scripts\fvid.exe\__main__.py", line 4, in <module>
  File "c:\users\tran bich dung\appdata\local\programs\python\python39\lib\site-packages\fvid\fvid.py", line 16, in <module>
    import magic
ModuleNotFoundError: No module named 'magic'
```

I don't know what happened. I tried to install 'magic':
```
E:\>py -m pip install magic
ERROR: Could not find a version that satisfies the requirement magic
ERROR: No matching distribution found for magic
```

And upgrade fvid to the latest master branch:
```
E:\>py -m pip install --upgrade git+https://github.com/AlfredoSequeida/fvid
Collecting git+https://github.com/AlfredoSequeida/fvid
  Cloning https://github.com/AlfredoSequeida/fvid to c:\users\tran bich dung\appdata\local\temp\pip-req-build-zyhpx15q
  Running command git clone -q https://github.com/AlfredoSequeida/fvid 'C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-req-build-zyhpx15q'
Requirement already satisfied: bitstring>=3.1.6 in c:\users\tran bich dung\appdata\local\programs\python\python39\lib\site-packages (from fvid==1.0.0) (3.1.7)
Requirement already satisfied: pillow>=7.2.0 in c:\users\tran bich dung\appdata\local\programs\python\python39\lib\site-packages (from fvid==1.0.0) (8.0.1)
Requirement already satisfied: tqdm>=4.49.0 in c:\users\tran bich dung\appdata\local\programs\python\python39\lib\site-packages (from fvid==1.0.0) (4.54.1)
Requirement already satisfied: cryptography>=3.1.1 in c:\users\tran bich dung\appdata\local\programs\python\python39\lib\site-packages (from fvid==1.0.0) (3.2.1)
Requirement already satisfied: pycryptodome>=3.9.8 in c:\users\tran bich dung\appdata\local\programs\python\python39\lib\site-packages (from fvid==1.0.0) (3.9.9)
Requirement already satisfied: six>=1.4.1 in c:\users\tran bich dung\appdata\local\programs\python\python39\lib\site-packages (from cryptography>=3.1.1->fvid==1.0.0) (1.15.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\users\tran bich dung\appdata\local\programs\python\python39\lib\site-packages (from cryptography>=3.1.1->fvid==1.0.0) (1.14.4)
Requirement already satisfied: pycparser in c:\users\tran bich dung\appdata\local\programs\python\python39\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=3.1.1->fvid==1.0.0) (2.20)
Building wheels for collected packages: fvid
  Building wheel for fvid (setup.py) ... done
  Created wheel for fvid: filename=fvid-1.0.0-py3-none-any.whl size=9930 sha256=23a8357e046bb26ea95a09bc2dd433ab5a1e4872a064e09f19ed726fba392229
  Stored in directory: C:\Users\Tran Bich Dung\AppData\Local\Temp\pip-ephem-wheel-cache-xf5q5eny\wheels\7d\29\2f\3abea42ac756b48077987d878a53a93f6ec3b1cee1c8560187
Successfully built fvid
Installing collected packages: fvid
  Attempting uninstall: fvid
    Found existing installation: fvid 1.0.1
    Uninstalling fvid-1.0.1:
      Successfully uninstalled fvid-1.0.1
Successfully installed fvid-1.0.0
```
But it still doesn't work...
Any help appreciated. Thanks!

**Comment by minhngoc25a** [comment]
Updating fvid from source takes longer time than updating youtube-dl from source. You should clean out that test folder.

Anyway, installing python-magic and zfec requires Microsoft Visual C++ 14.0, fvid should've included those out-of-the-box.

**Comment by Theelgirl** [comment]
> Anyway, installing python-magic and zfec requires Microsoft Visual C++ 14.0, fvid should've included those out-of-the-box.
Are you sure you installed MIcrosoft Visual C++ 14.0, because I installed it on my backup windows computer with Microsoft Visual C++ 14 and it worked fine. Also, how would fvid include those out-of-the-box? That's an appealing option, but I don't know how to do that.

**Comment by minhngoc25a** [comment]
I got it going. I downloaded a precompiled zfec and installed it. Apparently, on Windows, you have to install python-magic-bin to fetch libmagic's DLL.
