### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by YakirOren** [AlfredoSequeida/fvid#7]
I'm trying to run fvid and after installing all the modules im getting this error. 

```
C:\Users\Yakir Oren\Desktop\fvid>py fvid.py -i ./image.png -e

Traceback (most recent call last):
  File "fvid.py", line 275, in <module>
    make_video(video_file_path, image_sequence)
  File "fvid.py", line 200, in make_video
    ffmpeg.input(frames[0], loop=1, t=1).output(
  File "C:\Users\Yakir Oren\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\Yakir Oren\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\Yakir Oren\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Yakir Oren\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by dtaivpp** [comment]
It may be because of where your python is running. Try typing the fully qualified path for the input file, eg 'C:\Users\Yakir Oren\Desktop\fvid\image.png'

Python is funny with what it thinks is its root directory.

**Comment by AlfredoSequeida** [comment]
@YakirOren Yeah, try adding the full file path like @dtaivpp suggested and get back to us.

**Comment by YakirOren** [comment]
Hey the problem was on my part, I forgot to install the actual [ffmpeg ](https://ffmpeg.org/download.html)and not just the python lib. 😋
